/**
 * @file bridge_node.cpp
 * @author Peixuan Shu (shupeixuan@qq.com)
 * @brief Reliable TCP bridge for ros data transfer in unstable network.
 * It will send/receive the specified ROS topics in ../config/ros_topics.yaml
 * It uses zmq socket(PUB/SUB mode), which reconnects others autonomously and
 * supports 1-N pub-sub connection even with TCP protocol.
 *
 * Note: This program relies on ZMQPP (c++ wrapper around ZeroMQ).
 *  sudo apt install libzmqpp-dev
 *
 * Core Idea: It would create the receving thread for each receiving ROS topic
 *  and send ROS messages in each sub_cb() callback.
 *
 * @version 1.0
 * @date 2023-01-01
 *
 * @license BSD 3-Clause License
 * @copyright (c) 2023, Peixuan Shu
 * All rights reserved.
 *
 */

#include "bridge_node.hpp"
#include "control_server.hpp"
#include "sim_comm.hpp"

#include <cstring>
#include <utility>

// Namespace of this node, used to print relative topic names.
std::string ns; // namespace of this node

// Raw IP map parameter loaded from YAML.
XmlRpc::XmlRpcValue ip_xml;

// Raw send_topics parameter loaded from YAML.
XmlRpc::XmlRpcValue send_topics_xml;

// Raw recv_topics parameter loaded from YAML.
XmlRpc::XmlRpcValue recv_topics_xml;

// Number of configured send topics.
int len_send; // length(number) of send topics

// Number of configured receive topics.
int len_recv; // length(number) of receive topics

// Map from YAML logical host names to IP addresses.
std::map<std::string, std::string> ip_map; // map host name and IP

// Parsed metadata for outgoing topic streams.
std::vector<TopicInfo> sendTopics; // send topics info struct vector

// Parsed metadata for incoming topic streams.
std::vector<TopicInfo> recvTopics; // receive topics info struct vector

// Shared ZMQ context for all data-plane PUB/SUB sockets.
zmqpp::context_t context;

// Per-send-topic ZMQ PUB sockets.
std::vector<std::unique_ptr<zmqpp::socket>> senders;   //index senders

// Per-receive-topic ZMQ SUB sockets.
std::vector<std::unique_ptr<zmqpp::socket>> receivers; //index receivers

// ROS subscribers for local topics that should be bridged out.
std::vector<ros::Subscriber> topic_subs;

// ROS publishers for messages bridged in from remote nodes.
std::vector<ros::Publisher> topic_pubs;

// Per-send-topic frequency-control period start times.
std::vector<ros::Time> sub_t_last;

// Per-send-topic sent message count in the current frequency-control period.
std::vector<int> send_num;

// Per-receive-topic thread run flags.
std::vector<bool> recv_thread_flags;

// Previous receive result per topic, used for first-message logging.
std::vector<bool> recv_flags_last;

// Background threads for ZMQ receive loops.
std::vector<std::thread> recv_threads;

// /* send messages frequency control */
// // this is the original freq control func that has been deprecated
// bool send_freq_control(int i)
// {
//   ros::Time t_now = ros::Time::now();
//   bool discard_flag;
//   if ((t_now - sub_t_last[i]).toSec() * sendTopics[i].max_freq < 1.0) {
//     discard_flag = true;
//   }
//   else {
//     discard_flag = false;
//     sub_t_last[i] = t_now;
//   }
//   return discard_flag; // flag of discarding this message
// }

/**
 * Controls the maximum forwarding frequency for one send topic.
 *
 * Parameters:
 *   i: Index into sendTopics and frequency-control state vectors.
 *
 * Returns:
 *   true when the current message should be discarded; false when it may continue.
 *
 * Side Effects:
 *   Updates per-topic period start time and message count.
 */
bool send_freq_control(int i)
{
  bool discard_flag;
  ros::Time t_now = ros::Time::now();
  // check whether the send of this message will exceed the freq limit in the last period
  if ((send_num[i] + 1) / (t_now - sub_t_last[i]).toSec() > sendTopics[i].max_freq) {
    discard_flag = true;
  }
  else {
    discard_flag = false;
    send_num[i] ++;
  }
  // freq control period (1s)
  if ((t_now - sub_t_last[i]).toSec() > 1.0){
    sub_t_last[i] = t_now;
    send_num[i] = 0;
  }
  return discard_flag; // flag of discarding this message
}

/**
 * Uniform callback function for ROS subscribers generated by ros_sub_pub.hpp.
 *
 * Parameters:
 *   msg: Local ROS message received from the subscribed topic.
 *
 * Returns:
 *   None.
 *
 * Side Effects:
 *   Serializes the ROS message and submits it to sim_comm for fault/bandwidth control.
 */
template <typename T, int i>
void sub_cb(const T &msg)
{
  /* frequency control */
  auto ignore_flag = send_freq_control(i);
  if (ignore_flag){
    return; // discard this message sending, abort
  }

  /* serialize the sending message and hand it to the communication-control module */
  namespace ser = ros::serialization;
  size_t data_len = ser::serializationLength(msg); // bytes length of msg
  SimCommMessage send_message;
  send_message.data_len = data_len;
  send_message.data.resize(data_len);
  ser::OStream stream(send_message.data.data(), data_len);
  ser::serialize(stream, msg);

  dispatch_send_message(i, std::move(send_message));
  // std::cout << "send!" << std::endl;

  // std::cout << msg << std::endl;
  // std::cout << i << std::endl;
}


/**
 * Deserializes one received payload and publishes it to the local ROS topic.
 *
 * Parameters:
 *   buffer_ptr: Pointer to the serialized ROS payload.
 *   msg_size: Payload size in bytes.
 *   i: Index into recvTopics and topic_pubs.
 *
 * Returns:
 *   None.
 *
 * Side Effects:
 *   Publishes a message through topic_pubs[i].
 */
template<typename T>
void deserialize_pub(uint8_t* buffer_ptr, size_t msg_size, int i)
{
  T msg;
  // deserialize the receiving messages into ROS msg
  namespace ser = ros::serialization;
  ser::IStream stream(buffer_ptr, msg_size);
  ser::deserialize(stream, msg);
  // publish ROS msg
  topic_pubs[i].publish(msg);
}

/**
 * Submits one serialized received message through the normal ROS publish path.
 *
 * Parameters:
 *   buffer_ptr: Pointer to the serialized ROS payload.
 *   msg_size: Payload size in bytes.
 *   i: Index into recvTopics and topic_pubs.
 *
 * Returns:
 *   None.
 *
 * Side Effects:
 *   Dispatches to the type-specific deserializer and publishes locally.
 */
void publish_received_message(uint8_t* buffer_ptr, size_t msg_size, int i)
{
  deserialize_publish(buffer_ptr, msg_size, recvTopics[i].type, i);
}

/**
 * Receive-loop thread function for one incoming ZMQ topic stream.
 *
 * Parameters:
 *   i: Index into recvTopics, receivers, and receive-thread state vectors.
 *
 * Returns:
 *   None.
 *
 * Side Effects:
 *   Receives ZMQ payloads, hands them to sim_comm, and logs the first receive event.
 */
void recv_func(int i)
{
  while(recv_thread_flags[i])
  {
    /* receive and process message */
    zmqpp::message recv_array;
    bool recv_flag; // receive success flag
    // std::cout << "ready receive!" << std::endl;
    // receive(&,true) for non-blocking, receive(&,false) for blocking
    bool dont_block = false; // 'true' leads to high cpu load
    if (recv_flag = receivers[i]->receive(recv_array, dont_block))
    {
      // std::cout << "receive!" << std::endl;
      size_t data_len;
      recv_array >> data_len; // unpack meta data
      /*  equal to:
        recv_array.get(&data_len, recv_array.read_cursor++);
        void get(T &value, size_t const cursor){
          uint8_t const* byte = static_cast<uint8_t const*>(raw_data(cursor));
          b = *byte;}
      */
      SimCommMessage recv_message;
      recv_message.data_len = data_len;
      recv_message.data.resize(data_len);
      // continue to copy the raw_data of recv_array into buffer
      memcpy(recv_message.data.data(),
             static_cast<const uint8_t *>(recv_array.raw_data(recv_array.read_cursor())),
             data_len);
      dispatch_received_message(i, std::move(recv_message));

      // std::cout << data_len << std::endl;
      // std::cout << recv_buffer.get() << std::endl;
    }

    /* if receive() does not block, sleep to decrease loop rate */
    if (dont_block)
      std::this_thread::sleep_for(std::chrono::microseconds(1000)); // sleep for us
    else
    {
      /* check and report receive state */
      if (recv_flag != recv_flags_last[i]){
        std::string topicName = recvTopics[i].name;
        if (topicName.at(0) != '/') {
          if (ns == "/") {topicName = "/" + topicName;}
          else {topicName = ns + "/" + topicName;}
        }  // print namespace prefix if topic name is not global
        ROS_INFO("[bridge node] \"%s\" received!", topicName.c_str());
      } // false -> true(first message in)
      recv_flags_last[i] = recv_flag;
    }
  }
  return;
}

/**
 * Stops one send topic path.
 *
 * Parameters:
 *   i: Index into sendTopics, topic_subs, and senders.
 *
 * Returns:
 *   None.
 *
 * Side Effects:
 *   Unsubscribes the local ROS subscriber, stops bitrate control, and closes the ZMQ PUB socket.
 */
void stop_send(int i)
{
  topic_subs[i].shutdown(); // unsubscribe
  stop_send_bitrate_control(i);
  // senders[i]->unbind(std::string const &endpoint);
  senders[i]->close(); // close the send socket
}

/**
 * Stops one receive topic path.
 *
 * Parameters:
 *   i: Index into recvTopics, receivers, and topic_pubs.
 *
 * Returns:
 *   None.
 *
 * Side Effects:
 *   Requests the receive thread to finish, closes the ZMQ SUB socket, and unadvertises the ROS publisher.
 */
void stop_recv(int i)
{
  recv_thread_flags[i] = false; // finish recv_func()
  // receivers[i]->disconnect(std::string &endpoint);
  receivers[i]->close(); // close the receive socket
  topic_pubs[i].shutdown(); // unadvertise
}

//TODO: generate or delete topic message transfers through a remote zmq service.

/**
 * Bridge node entry point.
 *
 * Parameters:
 *   argc: ROS command-line argument count.
 *   argv: ROS command-line argument vector.
 *
 * Returns:
 *   Process exit code. Non-zero indicates configuration or startup failure.
 *
 * Side Effects:
 *   Initializes ROS/ZMQ resources, starts background threads, and runs ros::spin().
 */
int main(int argc, char **argv)
{
  ros::init(argc, argv, "swarm_bridge");
  ros::NodeHandle nh("~");
  ros::NodeHandle nh_public;
  ns = ros::this_node::getNamespace(); // namespace of this node

  std::cout << "--------[bridge_node]-------" << std::endl;
  std::cout << "namespaces=" << ns << std::endl;

  //************************ Parse configuration file **************************
  // get hostnames and IPs
  if (nh.getParam("IP", ip_xml) == false){
    ROS_ERROR("[bridge node] No IP found in the configuration!");
    return 1;
  }
  // get "send topics" params (topic_name, topic_type, IP, port)
  if (nh.getParam("send_topics", send_topics_xml)){
    ROS_ASSERT(send_topics_xml.getType() == XmlRpc::XmlRpcValue::TypeArray);
    len_send = send_topics_xml.size();
  }
  else{
    ROS_WARN("[bridge node] No send_topics found in the configuration!");
    len_send = 0;
  }
  // get "receive topics" params (topic_name, topic_type, IP, port)
  if (nh.getParam("recv_topics", recv_topics_xml)){
    ROS_ASSERT(recv_topics_xml.getType() == XmlRpc::XmlRpcValue::TypeArray);
    len_recv = recv_topics_xml.size();
  }
  else{
    ROS_WARN("[bridge node] No recv_topics found in the configuration!");
    len_recv = 0;
  }

  if (len_send > SUB_MAX)
  {
    ROS_FATAL("[bridge_node] The number of send topics in configuration exceeds the limit %d!", SUB_MAX);
    return 2;
  }

  std::cout << "-------------IP------------" << std::endl;
  for (auto iter = ip_xml.begin(); iter != ip_xml.end(); ++iter)
  {
    std::string host_name = iter->first;
    std::string host_ip = iter->second;
    std::cout << host_name << " : " << host_ip << std::endl;
    if (ip_map.find(host_name) != ip_map.end())
    { // ip_xml will never contain same names actually.
      ROS_WARN("[bridge node] IPs with the same name in configuration %s!", host_name.c_str());
    }
    ip_map[host_name] = host_ip;
  }

  std::cout << "--------send topics--------" << std::endl;
  std::set<int> srcPorts; // for duplicate check
  for (int32_t i=0; i < len_send; ++i)
  {
    ROS_ASSERT(send_topics_xml[i].getType() == XmlRpc::XmlRpcValue::TypeStruct);
    XmlRpc::XmlRpcValue send_topic_xml = send_topics_xml[i];
    std::string topic_name = send_topic_xml["topic_name"];
    std::string msg_type = send_topic_xml["msg_type"];
    int max_freq = send_topic_xml["max_freq"];
    double max_bitrate = get_optional_numeric_param(send_topic_xml, "max_bitrate", 0.0);
    std::string fault_policy = get_optional_string_param(send_topic_xml, "fault_policy", "drop");
    if (max_bitrate < 0.0)
    {
      ROS_FATAL("[bridge_node] max_bitrate of send topic \"%s\" must be greater than or equal to 0!",
                topic_name.c_str());
      return 3;
    }
    std::string srcIP = ip_map[send_topic_xml["srcIP"]];
    int srcPort = send_topic_xml["srcPort"];
    TopicInfo topic;
    topic.name = topic_name;
    topic.type = msg_type;
    topic.max_freq = max_freq;
    topic.max_bitrate = max_bitrate;
    topic.fault_policy = fault_policy;
    topic.ip = srcIP;
    topic.port = srcPort;
    sendTopics.emplace_back(topic);
    // check for duplicate ports:
    if (srcPorts.find(srcPort) != srcPorts.end()) {
      ROS_FATAL("[bridge_node] Send topics with the same srcPort %d in configuration!", srcPort);
      return 3;
    }
    srcPorts.insert(srcPort); // for duplicate check
    if (topic.name.at(0) != '/') {
      std::cout << ns;
      if (ns != "/") {std::cout << "/";}
    }  // print namespace prefix if topic.name is not global
    std::cout << topic.name << "  " << topic.max_freq << "Hz(max)";
    if (topic.max_bitrate > 0.0) {
      std::cout << "  " << topic.max_bitrate << "bps(max)";
    }
    std::cout << "  fault_policy=" << topic.fault_policy;
    std::cout << std::endl;
  }

  std::cout << "-------receive topics------" << std::endl;
  for (int32_t i=0; i < len_recv; ++i)
  {
    ROS_ASSERT(recv_topics_xml[i].getType() == XmlRpc::XmlRpcValue::TypeStruct);
    XmlRpc::XmlRpcValue recv_topic_xml = recv_topics_xml[i];
    std::string topic_name = recv_topic_xml["topic_name"];
    std::string msg_type = recv_topic_xml["msg_type"];
    std::string fault_policy = get_optional_string_param(recv_topic_xml, "fault_policy", "drop");
    std::string srcIP = ip_map[recv_topic_xml["srcIP"]];
    int srcPort = recv_topic_xml["srcPort"];
    TopicInfo topic;
    topic.name = topic_name;
    topic.type = msg_type;
    topic.max_freq = 0;
    topic.max_bitrate = 0.0;
    topic.fault_policy = fault_policy;
    topic.ip = srcIP;
    topic.port = srcPort;
    recvTopics.emplace_back(topic);
    if (topic.name.at(0) != '/') {
      std::cout << ns;
      if (ns != "/") {std::cout << "/";}
    }  // print namespace prefix if topic.name is not global
    std::cout << topic.name << "  (from " << recv_topic_xml["srcIP"]  << ")"
              << "  fault_policy=" << topic.fault_policy << std::endl;
  }

  // ********************* zmq socket initialize ***************************
  // send sockets (zmq socket PUB mode)
  for (int32_t i=0; i < len_send; ++i)
  {
    const std::string url = "tcp://" + sendTopics[i].ip + ":" + std::to_string(sendTopics[i].port);
    std::unique_ptr<zmqpp::socket> sender(new zmqpp::socket(context, zmqpp::socket_type::pub));
    sender->bind(url);
    senders.emplace_back(std::move(sender)); //sender is now released by std::move
  }
  initialize_send_bitrate_control(len_send);

  // receive sockets (zmq socket SUB mode)
  for (int32_t i=0; i < len_recv; ++i)
  {
    const std::string url = "tcp://" + recvTopics[i].ip + ":" + std::to_string(recvTopics[i].port);
    std::string const zmq_topic = ""; // "" means all zmq topic
    std::unique_ptr<zmqpp::socket> receiver(new zmqpp::socket(context, zmqpp::socket_type::sub));
    receiver->subscribe(zmq_topic);
    receiver->connect(url);
    receivers.emplace_back(std::move(receiver));
  }


  // ******************* ROS subscribe and publish *************************
  //ROS topic subsrcibe and send
  for (int32_t i=0; i < len_send; ++i)
  {
    sub_t_last.emplace_back(ros::Time::now()); // freq control period start time
    send_num.emplace_back(0); // the send messages number in a period
    ros::Subscriber subscriber;
    // The uniform callback function is sub_cb()
    subscriber = topic_subscriber(sendTopics[i].name, sendTopics[i].type, nh_public, i);
    topic_subs.emplace_back(subscriber);
    // use topic_subs[i].shutdown() to unsubscribe
  }

  // ROS topic receive and publish
  for (int32_t i=0; i < len_recv; ++i)
  {
    ros::Publisher publisher;
    publisher = topic_publisher(recvTopics[i].name, recvTopics[i].type, nh_public);
    topic_pubs.emplace_back(publisher);
  }

  // ****************** initialize simulated node-fault control ************
  initialize_node_fault_control(&publish_received_message);

  double node_fault_duration = 0.0;
  if (nh.getParam("node_fault_duration", node_fault_duration) && node_fault_duration > 0.0)
  {
    double node_fault_start_after = 0.0;
    nh.param("node_fault_start_after", node_fault_start_after, 0.0);
    schedule_node_fault(node_fault_start_after, node_fault_duration);
  }

  // ****************** launch remote fault-control server *****************
  ControlServerConfig control_config;
  nh.param("control_enabled", control_config.enabled, false);
  nh.param("control_node_id", control_config.node_id, std::string(""));
  nh.param("control_bind_ip", control_config.bind_ip, std::string("*"));
  nh.param("control_bind_port", control_config.bind_port, 3999);
  nh.param("control_token", control_config.token, std::string(""));
  if (control_config.node_id.empty())
  {
    control_config.node_id = ros::this_node::getName();
  }

  if (!start_control_server(control_config))
  {
    return 4;
  }

  // ****************** launch bitrate-control send threads ****************
  start_send_bitrate_threads();

  // ****************** launch receive threads *****************************
  for (int32_t i=0; i < len_recv; ++i)
  {
    recv_thread_flags.emplace_back(true); // enable receive thread flags
    recv_flags_last.emplace_back(false); // receive success flag
    recv_threads.emplace_back(std::thread(&recv_func, i));
  }

  ros::spin();

  // ***************** stop send/receive ******************************
  stop_control_server();
  stop_node_fault_control();

  for (int32_t i=0; i < len_send; ++i){
    stop_send(i);
  }

  for (int32_t i=0; i < len_recv; ++i){
    stop_recv(i);
  }
  
  return 0;
}
